### ISSUE TITLE
Can't get the layout to load

### ISSUE THREAD

**Issue by chester681** [bet4it/hyperinator#7] opened 2024-04-21 01:09 UTC
I have not been able to load a layout. I've tried reinstalling hyper but it did not help.

I have hyperinator installed

$ hyper i hyperinator
hyperinator is already installed

But it won't run
$ hyperinator load layout
bash: hyperinator: command not found

I'm using Git Bash as my shell in settings
shell: 'C:\\Program Files\\Git\\git-cmd.exe'

But It has the same result if I leave that setting blank.

Any idea? Is there a full path to hyperinator I can use?

**Comment by bet4it** [comment] 2024-04-21 11:47
Do you install it with `npm install -g hyperinator`? If so, `hyperinator` should be installed in `%APPDATA%\npm`.

**Comment by chester681** [comment] 2024-04-21 13:01
That was it. Thank you for the quick reply. I had so much trouble getting node and npm working correctly, then trying to get a few other plugins working that by the time i got to your plugin I thought that command was part of the old hpm-cli system before hyper created the "hyper" cli tool. So i didn't run it. Always something so simple. I appreciate your time.

**Comment by bet4it** [comment] 2024-04-21 14:41
If the problem is solved you could close this issue😀

**Closed as completed** 2024-04-21 16:00 UTC
